# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmf.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmf.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tcmf.proto\"\x1f\n\x0b\x43mfxRequest\x12\x10\n\x08\x63ontents\x18\x01 \x01(\t\"\x1e\n\x0b\x43hangeReply\x12\x0f\n\x07message\x18\x01 \x01(\t2i\n\x08\x45xecutor\x12-\n\rHandleCmfxMsg\x12\x0c.CmfxRequest\x1a\x0c.ChangeReply\"\x00\x12.\n\x0cHandleStream\x12\x0c.CmfxRequest\x1a\x0c.ChangeReply\"\x00(\x01\x62\x06proto3'
)




_CMFXREQUEST = _descriptor.Descriptor(
  name='CmfxRequest',
  full_name='CmfxRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contents', full_name='CmfxRequest.contents', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=44,
)


_CHANGEREPLY = _descriptor.Descriptor(
  name='ChangeReply',
  full_name='ChangeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ChangeReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['CmfxRequest'] = _CMFXREQUEST
DESCRIPTOR.message_types_by_name['ChangeReply'] = _CHANGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CmfxRequest = _reflection.GeneratedProtocolMessageType('CmfxRequest', (_message.Message,), {
  'DESCRIPTOR' : _CMFXREQUEST,
  '__module__' : 'cmf_pb2'
  # @@protoc_insertion_point(class_scope:CmfxRequest)
  })
_sym_db.RegisterMessage(CmfxRequest)

ChangeReply = _reflection.GeneratedProtocolMessageType('ChangeReply', (_message.Message,), {
  'DESCRIPTOR' : _CHANGEREPLY,
  '__module__' : 'cmf_pb2'
  # @@protoc_insertion_point(class_scope:ChangeReply)
  })
_sym_db.RegisterMessage(ChangeReply)



_EXECUTOR = _descriptor.ServiceDescriptor(
  name='Executor',
  full_name='Executor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=78,
  serialized_end=183,
  methods=[
  _descriptor.MethodDescriptor(
    name='HandleCmfxMsg',
    full_name='Executor.HandleCmfxMsg',
    index=0,
    containing_service=None,
    input_type=_CMFXREQUEST,
    output_type=_CHANGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HandleStream',
    full_name='Executor.HandleStream',
    index=1,
    containing_service=None,
    input_type=_CMFXREQUEST,
    output_type=_CHANGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXECUTOR)

DESCRIPTOR.services_by_name['Executor'] = _EXECUTOR

# @@protoc_insertion_point(module_scope)
